# Erzwingt den reinen USB-Betrieb und deaktiviert fehlerhaftes Logging
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_LOGGING=n

# Schaltet alle Peripherie-Treiber ab, die den Absturz verursachen könnten
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_EXT_POWER=n

# Bluetooth-Grundkonfiguration
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
