# Zwingt die Tastatur, die Daten IMMER über USB an Windows zu senden
CONFIG_ZMK_USB=y

# Setzt USB als bevorzugtes Ausgabemedium (ignoriert die Bluetooth-Warteschleife)
CONFIG_ZMK_BLE=n
CONFIG_ZMK_USB_BOOT=y

# Schaltet fehlerhafte Logs ab, die den USB-Kanal blockieren könnten
CONFIG_ZMK_USB_LOGGING=n

# Schaltet die Stromkontrolle ab, um Klon-Abstürze zu verhindern
CONFIG_ZMK_EXT_POWER=n
